from typing import Dict, Any
from backend.agents.base import BaseWorkforceAgent
from backend.core.models import SharedCompanyContext, MarketContext
from backend.events.bus import EventBus
from backend.events.models import EventType
from backend.agents.model_provider import model_provider
from backend.context.manager import context_manager
from backend.artifacts.manager import artifact_manager

class ResearchAgent(BaseWorkforceAgent):
    """
    Market Intelligence & Problem-Solution Analyst.
    Discovers target ICP, analyzes competitors, evaluates core pain, and documents assumptions.
    """
    def __init__(self):
        super().__init__(
            name="ResearchAgent",
            role="Market Intelligence Specialist",
            description="Analyzes market viability, customer ICP, competitors, and strategic opportunities.",
            allowed_tools=["web_search_stub", "write_workspace_file"]
        )

    def validate_input(self, context: SharedCompanyContext) -> bool:
        return context.project_goal is not None and bool(context.project_goal.raw_intent.raw_input)

    async def run(
        self,
        session_id: str,
        context: SharedCompanyContext,
        bus: EventBus
    ) -> Dict[str, Any]:
        raw_intent = context.project_goal.raw_intent.raw_input
        
        # Step 1: Tool invocation for competitor research
        await self.publish_event(
            bus=bus,
            session_id=session_id,
            event_type=EventType.TOOL_STARTED,
            status="RUNNING",
            message="Scanning market competitors and audience demographics",
            payload={"tool": "web_search", "query": raw_intent[:50]}
        )

        research_data = await model_provider.generate_structured(
            prompt=raw_intent,
            system_instruction="Analyze the business concept. Formulate target ICP, core pain points, 3 competitors, and market wedge.",
            stage="research"
        )

        await self.publish_event(
            bus=bus,
            session_id=session_id,
            event_type=EventType.TOOL_COMPLETED,
            status="COMPLETED",
            message=f"Found {len(research_data.get('competitors', []))} benchmark competitors",
            payload={"competitors_count": len(research_data.get('competitors', []))}
        )

        # Step 2: Build MarketContext and update shared context
        market_ctx = MarketContext(
            target_icp=research_data.get("target_icp", "Early Adopter Business Owners"),
            demographics=["Tier 1 & 2 Indian Cities", "Independent Practices / MSMEs"],
            core_pain_points=[research_data.get("core_pain", "Inefficient manual workflows")],
            competitors=research_data.get("competitors", []),
            market_opportunities=research_data.get("market_opportunities", []),
            key_assumptions=research_data.get("key_assumptions", [])
        )
        await context_manager.update_market(session_id, market_ctx)

        # Step 3: Write research_brief.md artifact
        competitors_md = "\n".join([
            f"- **{c.get('name')}**: Strength: {c.get('strength')}. Gap: {c.get('weakness') or c.get('gap')}"
            for c in market_ctx.competitors
        ])
        opportunities_md = "\n".join([f"- {opp}" for opp in market_ctx.market_opportunities])
        assumptions_md = "\n".join([f"- {asm}" for asm in market_ctx.key_assumptions])

        md_content = f"""# Market Intelligence & Research Brief

**Project:** {context.project_goal.project_name}  
**Target Domain:** {context.project_goal.industry_domain}  
**Generated By:** Udyam OS Research Agent  

---

## 1. Ideal Customer Profile (ICP)
{market_ctx.target_icp}

---

## 2. Acute Core Customer Problem
{market_ctx.core_pain_points[0]}

---

## 3. Competitive Landscape & Market Gaps
{competitors_md}

---

## 4. Strategic Market Opportunities (The Wedge)
{opportunities_md}

---

## 5. Critical Business Assumptions to Validate
{assumptions_md}
"""

        await artifact_manager.create_artifact(
            session_id=session_id,
            artifact_id="art_research_brief",
            artifact_type="research_brief",
            title="Market & Competitor Analysis",
            relative_path="research_brief.md",
            created_by=self.name,
            content=md_content
        )

        return research_data
